### ISSUE TITLE
My system setup is preventing me from using this very nice package :-(

### ISSUE THREAD

**Issue by js8765** [cjdinger/SasHarness#1]
Hi, 

Firstly, just to be clear, the below is not a problem with SasHarness but rather with my setup. I just thought I would share it in case someone else has had the same problem or experiences it later on.

I have the following setup:
- Visual Studio Express on my 64-bit Windows machine
- SAS on a 32-bit server
- I've copied the 32-bit DLLs to my 64-bit machine and referenced them in SasHarness.
- I've set my platform target in Visual Studio Express to X86

Unfortunately I keep getting the following error when the program tries to access SASObjectManager.ObjectKeeper
"Retrieving the COM class factory for component with CLSID {D6979A22-6B31-11D5-BA37-00C04F81BC00} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))."

I've tried setting the Configuration Manager values to X86 but nothing seems to resolve this issue. If anyone has any advice, it would be greatly appreciated.

Thanks!

**Comment by cjdinger** [comment]
You do need the SAS Integration Technologies client package installed on your PC in order to use this at runtime.  This package will register the client pieces needed to connect to the remote SAS session.  The IntTech client is installed as part of SAS Enterprise Guide and other SAS products, or you can download (for free) and install it yourself:

http://support.sas.com/downloads/browse.htm?fil=&cat=56

**Comment by js8765** [comment]
Thanks a lot. That worked very well. 

I'd like to warn others to make sure to download the correct version of the SAS Integration Technologies client package i.e. the one that corresponds to the version of SAS that is installed. I downloaded the latest version without thinking but this was for SAS 9.4 which I did not have installed.

**Comment by cjdinger** [comment]
Glad it's working for you!  The 9.4 client _should_ work even with back-level versions of SAS, at least going back to SAS 9.2.
