### ISSUE TITLE
Error: The client has connected to a SAS Metadata server (v1.0) when it intended to connect to a SAS Workspace server

### ISSUE THREAD

**Issue by ArunGanesh-GIT** [cjdinger/SasHarness#2]
Hi,

I keep getting this error using the tool - "The client has connected to a SAS Metadata server (v1.0) when it intended to connect to a SAS Workspace server". I have verified the SAS workspace server name, machine dns name and the port with my SAS admin and these input looks correct. Could you please help me resolve this? Am i missing something? We are using SAS 9.4. I'm connecting to SAS using VS2017 from a 64 bit machine.

Thanks,

**Comment by cjdinger** [comment]
You are probably connecting to the Metadata server port (default: 8561) instead of the Workspace server port (default: 8591).  If using EG, your connection info includes the Metadata server, which then retrieves the list of available workspace servers (ex: "SASApp") and brokers the Workspace connection for you.  With this app example, we're bypassing the Metadata server and going straight to the Workspace.

**Comment by SivaAllam12** [comment]
Hey, i didn't get what you said. Could you please elaborate. Do i need to change the 'iom host'? Im also getting the same error. Thanks.

**Comment by cjdinger** [comment]
@SivaAllam12 -- The different types of SAS servers "listen" on different ports.  Also, it is possible that your metadata server is a different host than your Workspace server.  Best advice is to check your "SASApp" properties in a client (like EG) when you're connected, and note the host and port -- then use those here.

**Comment by SivaAllam12** [comment]
@cjdinger-- yes.  i can connect now. Thank you so much for help :)

**Comment by sbasra-epi** [comment]
> [@SivaAllam12](https://github.com/SivaAllam12) -- The different types of SAS servers "listen" on different ports. Also, it is possible that your metadata server is a different host than your Workspace server. Best advice is to check your "SASApp" properties in a client (like EG) when you're connected, and note the host and port -- then use those here.

Thanks, that helped me as well.
