### ISSUE TITLE
Return Error

### ISSUE THREAD

**Issue by 13555977885** [cjdinger/SasHarness#3]
{"<?xml version=\"1.0\" ?><Exceptions><Exception><SASMessage severity=\"Error\">SQL passthru 表达式包含以下错误: ERROR 22-322: 语法错误，期望下列之一: 名称, 带引号的字符串, (, CONNECTION, DICTIONARY....  ERROR 200-322: 该符号不可识别，将被忽略。...  ERROR 22-322: 语法错误，期望下列之一: 名称, 带引号的字符串, 数值常数, 日期时间常数, 缺失值, BTRIM, INPUT, PUT, SUBSTRING, USER....  ERROR 22-322: 语法错误，期望下列之一: !, !!, &amp;, *, **, +, -, /, &lt;, &lt;=, &lt;&gt;, =, &gt;, &gt;=, ?, AND, CONTAINS, EQ, EQT, GE, GET, GROUP, GT, GTT, HAVING, LE, LET, LIKE, LT, LTT, NE, NET, OR, ORDER, ^=, |, ||, ~=....  ERROR 76-322: 语法错误，语句将被忽略。</SASMessage></Exception></Exceptions>"}

**Comment by cjdinger** [comment]
Is this an error you're seeing when trying to use the data viewer?  I'll need more information and maybe screenshots to see what's going on.

**Comment by cjdinger** [comment]
Closing for now -- but feel free to come back if you have more info.
